##
# @date signals.yaml
# @date 19.05.2016
#
# @brief Signal specifications for the CAN gateway and the monitors.
#
# 'signals/names' must include all the signals of interest, i.e., signals that
# should be passed to ROS.
#
# Parameters of a signal:
# - topic
# - direction: take one of ["both"|"publish"|"subscribe"]
# - id: CAN ID (standard 11 bits or extended 29 bits)
# - position: starting position in bits of the signal
# - length: length of signal in bits. <= 64 (8 bytes)
# - isSigned: take one of [true|false]. Will be cast to a signed integer if 'true'.
# - resolution: data will be multiplied with this value.
# - offset: will be added to the data.
# - period: period in seconds of the signal (needed by the monitor).
# - min/max: range of the signal (needed by the monitor).
#
# @note Currently only signals up to 8 bytes are supported.
##

signals:

  names: ["battery_voltage", "battery_current", "battery_soc", "battery_soh"]

  battery_voltage:
    topic: "/pestnu/battery_voltage"
    direction: "publish"
    id: 0x780
    position: 0
    length: 16
    isSigned: false
    resolution: 0.010
    offset: 0.0
    period: 0.2
    min: 0.0
    max: 6000
    # in 10 mV

  battery_current:
    topic: "/pestnu/battery_current"
    direction: "publish"
    id: 0x780
    position: 16
    length: 16
    isSigned: true
    resolution: 0.010
    offset: 0.0
    period: 0.2
    min: -7200
    max: 7200
    # in 10 mA

  battery_soc:
    topic: "/pestnu/battery_soc"
    direction: "publish"
    id: 0x780
    position: 32
    length: 16
    isSigned: false
    resolution: 0.01
    offset: 0.0
    period: 0.2
    min: 0
    max: 10000
    # in 0.01 %

  battery_soh:
    topic: "/pestnu/battery_soh"
    direction: "publish"
    id: 0x780
    position: 48
    length: 16
    isSigned: false
    resolution: 0.01
    offset: 0.0
    period: 0.2
    min: 0
    max: 10000
    # in 0.01 %